# Team

0228903 Juan Pablo Enríquez Pedroza

0229261 Ulises Gallardo Rodríguez

# PSO

In [43]:
from scipy.optimize import linprog
import numpy as np
np.set_printoptions(suppress=True)

from PSO import particle_swarm_optimization

In [44]:
def linear_f(X, A,b,c, bounds):
    Valid_Solution = True
    
    for bound in bounds:
        for value in X:
            if bound[0]!=None:
                if value<bound[0]: Valid_Solution = False
            if bound[1]!=None:
                if value>bound[1]: Valid_Solution = False
    
    for i in range(len(A)):
        res = 0
        for j in range(len(A[0])):
            res+=A[i][j] * X[j]
        if not(res <= b[i]):
             Valid_Solution = False
        
    if Valid_Solution:
        sum = 0
        for i, val in enumerate(X):
            sum+=c[i]*val
        return sum
    else:
        return 1000000

### Problem 1
$$ Max 20000p + 15000m $$
$$ S.A. $$
$$ p + 2m <= 80 $$
$$ 3p + 2m <= 120 $$
$$ p,m >= 0 $$

In [45]:
A = [[1,2],
     [3,2]]
b = [ 80,
     120]
bounds = [[0,None],
          [0,None]]
c = [-20000,-15000]

print(linprog(c, A_ub=A, b_ub=b, A_eq=None, b_eq=None,bounds=bounds))
print("\nOwn implementation:\n",particle_swarm_optimization(linear_f,100,bounds,args=((A,b,c,bounds)), N = 100))

     con: array([], dtype=float64)
     fun: -849999.9999227368
 message: 'Optimization terminated successfully.'
     nit: 7
   slack: array([0.00000001, 0.00000001])
  status: 0
 success: True
       x: array([20., 30.])
rep:  1 / 1

Own implementation:
 (array([20.02221097, 29.95892859]), 100, -849828.1482561682, 10100)


![alternative text](1.jpg)

### Problem 2
$$ Max  20L1 + 10L2 $$
$$ S.A. $$
$$ 20L1 + 30L2 <= 6000 $$
$$ 10L1 + 10L2 <= 4800 $$
$$ L1,L2 >= 0 $$

In [46]:
A = [[20,30],
     [10,10]]
b = [6000,
     4800]
bounds = [[0,None],
          [0,None]]
c = [-20,-10]

print(linprog(c, A_ub=A, b_ub=b, A_eq=None, b_eq=None,bounds=bounds))
print("\nOwn implementation:\n",particle_swarm_optimization(linear_f,100,bounds,args=((A,b,c,bounds)), N = 100))

     con: array([], dtype=float64)
     fun: -5999.999344195026
 message: 'Optimization terminated successfully.'
     nit: 5
   slack: array([   0.00061665, 1800.00031811])
  status: 0
 success: True
       x: array([299.99996623,   0.00000196])
rep:  1 / 1

Own implementation:
 (array([299.99999962,   0.00000014]), 100, -5999.999993818899, 10100)


![alternative text](2.jpg)

### Problem 3
$$ Min  10X + 30Y $$
$$ S.A. $$
$$ X + 5Y >= 15 $$
$$ 5X + Y >= 15 $$
$$ X,Y > 0 $$

In [47]:
A = [[-1,-5],
     [-5,-1]]
b = [-15,
     -15]
bounds = [[1,None],
          [1,None]]
c = [10,30]


print(linprog(c, A_ub=A, b_ub=b, A_eq=None, b_eq=None,bounds=bounds))
print("\nOwn implementation:\n",particle_swarm_optimization(linear_f,100,bounds,args=((A,b,c,bounds)), N = 100))

     con: array([], dtype=float64)
     fun: 99.9999999995525
 message: 'Optimization terminated successfully.'
     nit: 4
   slack: array([-0., -0.])
  status: 0
 success: True
       x: array([2.5, 2.5])
rep:  1 / 1

Own implementation:
 (array([2.50005521, 2.49999683]), 100, 100.00045687848038, 10100)


![alternative text](3.jpg)

### Problem 4
$$ Max  6.5X + 7Y $$
$$ S.A. $$
$$ 2X + 3Y <= 600 $$
$$ X + Y <= 500 $$
$$ 2X + Y <= 400 $$
$$ X,Y >= 0 $$

In [48]:
A = [[2,3],
     [1,1],
     [2,1]]
b = [600,
     500,
     400]
bounds = [[0,None],
          [0,None]]
c = [-6.5,-7]

print(linprog(c, A_ub=A, b_ub=b, A_eq=None, b_eq=None,bounds=bounds))
print("\nOwn implementation:\n",particle_swarm_optimization(linear_f,100,bounds,args=((A,b,c,bounds)), N = 100))

     con: array([], dtype=float64)
     fun: -1674.9999979637923
 message: 'Optimization terminated successfully.'
     nit: 5
   slack: array([  0.00000073, 250.0000003 ,   0.00000049])
  status: 0
 success: True
       x: array([149.99999981,  99.99999988])
rep:  1 / 1

Own implementation:
 (array([149.99989466,  99.99987781]), 100, -1674.9984599853956, 10100)


![alternative text](4.jpg)


### Problem 5
$$ Min  800G + 600P $$
$$ S.A. $$
$$ 50G + 40P <= 400 $$
$$ P + G <= 9 $$
$$ 0<=X,Y <= 8 $$

In [49]:
A = [[-50,-40],
     [1,1]]
b = [-400,
     9]
bounds = [[1,9],
          [1,8]]
c = [800,600]

print(linprog(c, A_ub=A, b_ub=b, A_eq=None, b_eq=None,bounds=bounds))
print("\nOwn implementation:\n",particle_swarm_optimization(linear_f,200,bounds,args=((A,b,c,bounds)), N = 150))

     con: array([], dtype=float64)
     fun: 6199.999985825726
 message: 'Optimization terminated successfully.'
     nit: 6
   slack: array([-0.00000087,  0.00000002])
  status: 0
 success: True
       x: array([3.99999998, 5.00000001])
rep:  1 / 1

Own implementation:
 (array([4., 5.]), 200, 6200.000000000004, 30150)


![alternative text](5.jpg)